controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
      - joint8
  - name: fake_robot_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint8
      - joint9
initial:  # Define initial robot poses per group
  - group: robot_arm
    pose: initial