tag_family:        'tag36h11' # Семейство маркеров (варианты: tagStandard52h13, tagStandard41h12, tag36h11 и т.д.)
tag_threads:       2          # Количество потоков для обработки изображений.
tag_decimate:      1.0        # Масштабирование изображения перед обработкой (1.0 — без изменений).
tag_blur:          0.0        # Размытие изображения для подавления шума (0 — отключено).
tag_refine_edges:  1          # Уточнение краев маркеров (1 — включено).
tag_debug:         0          # Режим отладки (0 — отключено).
max_hamming_dist:  2          # Максимальная дистанция Хэмминга (2 — хороший выбор для надежности).

# Другие параметры
publish_tf:        true       # Публикация данных в формате TF (для работы с пространственными координатами).
transport_hint:    "raw"      # Тип транспорта изображения (raw, compressed и т.д.).